apiVersion: apps/v1
kind: Deployment
metadata:
  name: zhvdg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zhvdg
  template:
    metadata:
      labels:
        app: zhvdg
    spec:
      containers:
      - image: okteto.dev/zhvdg:latest
        name: zhvdg
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "6a8fc9f2-5b9e-4bac-9e3d-8552553ed416"
        - name: Vless_Path
          value: "/vl55csdu"
        - name: Vmess_UUID
          value: "6a8fc9f2-5b9e-4bac-9e3d-8552553ed416"
        - name: Vmess_Path
          value: "/vlagcs76u"
        - name: Share_Path
          value: "/v2link"
